In [1]:
import numpy as np

## Data types and attributes

In [2]:
# Numpy main datatype is nd array
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [7]:
type(a1)

numpy.ndarray

In [8]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [9]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
np.random.seed(7)
narray = np.random.randint(0,10,size = (3,5))

In [20]:
narray

array([[4, 9, 6, 3, 3],
       [7, 7, 9, 7, 8],
       [9, 8, 7, 6, 4]])

In [23]:
narray = np.random.randint(0,10,size = (3,5))
narray

array([[7, 9, 3, 0, 7],
       [7, 7, 0, 5, 4],
       [3, 1, 3, 1, 3]])

## This is the begining of the mini `numpy project` 